---
apiVersion: apps/v1 # Note the changes from Pod file
kind: Deployment # Note the change
metadata:
  name: k8s-bootcamp-deploy
  labels:
    app: k8s-bootcamp-app
spec:
  replicas: 1 # number of replicas
  selector: # selector
    matchLabels:
      app: k8s-bootcamp # this should match the Pod label in spec
  template: # template
    metadata:
      name: k8s-bootcamp-pod
      labels:
        app: k8s-bootcamp # Pod label
    spec:
      containers:
      - name: k8s-bootcamp-container
        image: suhasab/python-flask-app:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-bootcamp-svc
  labels:
    app: k8s-bootcamp-app
spec:
  type: NodePort # Default is ClusterIP if not specified
  selector:
    app: k8s-bootcamp # match the Pod label
  ports:
  - port: 8888
